apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
  namespace: ticketing
spec:
  serviceName: order-db
  replicas: 1
  selector: { matchLabels: { app: order-db } }
  template:
    metadata: { labels: { app: order-db } }
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports: [{ containerPort: 5432 }]
        env:
        - { name: POSTGRES_DB,   value: orderdb }
        - { name: POSTGRES_USER, value: postgres }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: pg-secrets, key: POSTGRES_PASSWORD } }
        volumeMounts:
        - { name: data, mountPath: /var/lib/postgresql/data }
        readinessProbe:
          exec: { command: ["pg_isready","-U","postgres"] }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec: { command: ["pg_isready","-U","postgres"] }
          initialDelaySeconds: 15
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata: { name: data }
    spec:
      accessModes: ["ReadWriteOnce"]
      resources: { requests: { storage: 2Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: ticketing
spec:
  selector: { app: order-db }
  ports: [{ port: 5432, targetPort: 5432 }]
